# +----------------------------------------------------+ #
# <     Jellteks Guilds Global Configuration File      > #
# <     This configuration file will apply to all      > #
# <                      guilds.                       > #
# +----------------------------------------------------+ #

guildCreation:
    chargeAmount: 1000.0
    defaultTag: "DEFTAG"
    useColourCodesInTag: true
    defaultMotd: "This is the default guild MOTD."
    